import type { JavaField } from '../../types.js'
import { camelToSnake } from '../../utils/naming.js'

export interface SqlDiffInput {
  newTable: string
  oldFields: JavaField[]
  newFields: JavaField[]
}

export function generateSqlServerDiff(input: SqlDiffInput): string {
  const { newTable, oldFields, newFields } = input

  const oldNames = new Set(oldFields.map(f => f.name))
  const newNames = new Set(newFields.map(f => f.name))

  const added = newFields.filter(f => !oldNames.has(f.name))
  const removed = oldFields.filter(f => !newNames.has(f.name))

  const lines: string[] = []
  lines.push(`-- Auto generated by refactor-agent: SQL Server idempotent diff`)
  lines.push(`-- Target table: dbo.${newTable}`)
  lines.push('')

  // Added columns
  for (const f of added) {
    const col = camelToSnake(f.name)
    const sqlType = mapJavaTypeToSqlServer(f.type)
    lines.push(`-- ADD COLUMN ${col} (${f.type}) ${f.comment ?? ''}`)
    lines.push(`IF COL_LENGTH('dbo.${newTable}', '${col}') IS NULL`)
    lines.push(`BEGIN`)
    lines.push(`    ALTER TABLE dbo.${newTable} ADD ${col} ${sqlType} NULL;`)
    if (f.comment) {
      lines.push(`    EXEC sys.sp_addextendedproperty`)
      lines.push(`        @name = N'MS_Description', @value = N'${f.comment.replace(/'/g, "''")}',`)
      lines.push(`        @level0type = N'SCHEMA', @level0name = N'dbo',`)
      lines.push(`        @level1type = N'TABLE',  @level1name = N'${newTable}',`)
      lines.push(`        @level2type = N'COLUMN', @level2name = N'${col}';`)
    }
    lines.push(`END;`)
    lines.push(`GO`)
    lines.push('')
  }

  // Removed columns
  for (const f of removed) {
    const col = camelToSnake(f.name)
    lines.push(`-- DROP COLUMN ${col}`)
    // 1) drop default constraint
    lines.push(`DECLARE @df_${col} NVARCHAR(128);`)
    lines.push(`SELECT @df_${col} = dc.name FROM sys.default_constraints dc`)
    lines.push(`  JOIN sys.columns c ON c.default_object_id = dc.object_id`)
    lines.push(`  WHERE dc.parent_object_id = OBJECT_ID(N'dbo.${newTable}') AND c.name = N'${col}';`)
    lines.push(`IF @df_${col} IS NOT NULL`)
    lines.push(`    EXEC(N'ALTER TABLE dbo.${newTable} DROP CONSTRAINT ' + QUOTENAME(@df_${col}));`)
    lines.push(`GO`)
    // 2) drop extended property if exists
    lines.push(`IF EXISTS (`)
    lines.push(`    SELECT 1 FROM sys.extended_properties ep`)
    lines.push(`    JOIN sys.columns c ON ep.major_id = c.object_id AND ep.minor_id = c.column_id`)
    lines.push(`    WHERE ep.name = N'MS_Description'`)
    lines.push(`      AND c.object_id = OBJECT_ID(N'dbo.${newTable}') AND c.name = N'${col}'`)
    lines.push(`)`)
    lines.push(`    EXEC sys.sp_dropextendedproperty`)
    lines.push(`        @name = N'MS_Description',`)
    lines.push(`        @level0type = N'SCHEMA', @level0name = N'dbo',`)
    lines.push(`        @level1type = N'TABLE',  @level1name = N'${newTable}',`)
    lines.push(`        @level2type = N'COLUMN', @level2name = N'${col}';`)
    lines.push(`GO`)
    // 3) drop column
    lines.push(`IF COL_LENGTH('dbo.${newTable}', '${col}') IS NOT NULL`)
    lines.push(`    ALTER TABLE dbo.${newTable} DROP COLUMN ${col};`)
    lines.push(`GO`)
    lines.push('')
  }

  if (added.length === 0 && removed.length === 0) {
    lines.push(`-- No field difference detected. Table is in sync.`)
  }

  return lines.join('\n') + '\n'
}

function mapJavaTypeToSqlServer(type: string): string {
  switch (type) {
    case 'String':
      return 'nvarchar(255)'
    case 'Long':
    case 'long':
      return 'bigint'
    case 'Integer':
    case 'int':
      return 'int'
    case 'Boolean':
    case 'boolean':
      return 'bit'
    case 'BigDecimal':
      return 'decimal(18,4)'
    case 'LocalDateTime':
    case 'Date':
      return 'datetime2(3)'
    case 'LocalDate':
      return 'date'
    default:
      return 'nvarchar(255)'
  }
}
